### ISSUE TITLE
Add OBS tN and KT as a Project

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#195]
We need to get the translationNotes and Key/Important Terms available as a separate project for translation in tS.  The tN shouldn't be a problem as it basically follows the book-chapter-verse sort of layout.  For the key terms, we may want to create a pseudo layout, perhaps just based on the alphabet?  Examples:

OBS --> Story 1 -> Frame 1 (this is how OBS is setup)
tN -- > Story 1 -> Frame 1
KT -- > A -> Aaron

Do you think we could make that work, @neutrinog ?

**Comment by neutrinog** [comment]
Yes I think that would work with a little configuration.

**Comment by neutrinog** [comment]
We'll probably need to make the source ref and title optional so if they are empty or missing the user will not be asked (or able) to translate them.

**Comment by neutrinog** [comment]
this also needs to be at level 3 to be used. just like the source text.

**Comment by neutrinog** [comment]
these will be completely separate projects. in the same way that projects are organized into categories we will organize the notes and kt into categories (we can use the project meta for this).

**Comment by neutrinog** [comment]
Just putting some thoughts down. We can farm out the key term and notes catalogs from projects in initProjects and reloadProject. We can create a custom TermsProject and NotesProject that extends the Project class. These classes will allow the model list adapter to correctly identify the different project types.

**Comment by neutrinog** [comment]
@jag3773 

I've encountered some issues with how to implement the ui for notes and terms projects.

We will need to have a project for each set of notes because notes are not shared between projects.
Key terms are different. we can just have a single project for key terms in the Bible and one for key terms in OBS.
However, notes are currently unique to each project so we will indeed have 66 new projects just for the notes in Bible projects.

I've also encountered another problem with the notes. They don't really fit the model we have for standard projects because rather than having just a set of raw text for the notes it's broken up into references. So one note will have half a dozen pieces each with a reference and text. Therefore, the UI for translating notes will have to be different from traditional translation projects.

Ideas?

**Comment by neutrinog** [comment]
For the notes we can keep the current navigation, but place a "translate" button in the translation notes drawer that will display an interface for translating those notes.

**Comment by neutrinog** [comment]
the ui for this is mostly finished. Just need to hook up the backend now.

**Comment by neutrinog** [comment]
In order to provide full support for translating notes from any gateway language we need to have an id on each note field. However, for the time being there is no id field, and the only notes available are in english. So we will generate the id for the translation dynamically using the selected getway language (always english in this case) reference and the chapter + frame id.

e.g. `01-01 the beginning`

This will provide the correct id in the translation, however we will need to add these id's in the api and update the implimentation to use these id's when we begin to provide notes for other gateway languages.

See https://github.com/Door43/translationStudio2/issues/465

**Comment by neutrinog** [comment]
@jag3773 for now I'm using an md5 sum of the chapter, frame, and reference  for the id in order to create an id without any special characters. Because the id needs to be usable in a file name.

This only needs to matter within git and syncing to the server. We can merge everything together using the non-md5 version of the id once it's on the server.

**Comment by neutrinog** [comment]
need to display translation notes projects in the Backup and publish actvity.
