### ISSUE TITLE
Graphite Support

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#344]
Add graphite support.

**Comment by neutrinog** [comment]
could you provide some details on what languages this is important for.
it'll be hard to implement if I don't' have a baseline to test from.

e.g. font to use, language to use, expected output (Screen shots).

**Comment by jag3773** [comment]
Take a look at https://github.com/silnrsi/grandroid.

**Comment by neutrinog** [comment]
This is mostly implemented. There are a few locations in the app that will need to be updated to utilize graphite, but most of the main areas are already hooked up. I'll wait for some feedback before closing this.

**Comment by jag3773** [comment]
Is this implemented in source and and text entry boxes?

**Comment by neutrinog** [comment]
source, library, and the translation input. I did not add it to all input entries yet.

**Comment by neutrinog** [comment]
we will provide graphite support for those versions of android that support it. Otherwise it will fall back to normal text. We should be able to keep it all in on apk and just check the os version.

**Comment by neutrinog** [comment]
I've got everything set up but am leaving it disabled for now. If we enable grandroid then we can't use x86 emulators due to the lack of an x86 build of grandroid. I've left them an issue requesting a build in x86 https://github.com/silnrsi/grandroid/issues/7. Not being able to use an x86 emulator is a HUGE roadblock to development, because the arm emulators are practically worthless and often don't even boot up correctly.

**Comment by dsm-git** [comment]
Can you add a hook to disable graphite on those platforms, similar to the
Android 5 exclusion?

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by neutrinog** [comment]
I can disable graphite, but the problem comes with the compiling and installation.
When installing the app it notices a library is missing for it's architecture and errors out.

I can get around that by creating a custom build variant that excludes all the graphite libraries, and then manually installing the apk. This process works but is much longer than just clicking on the debug button in the ide. It's also a slightly convoluted process that we'll need to teach all new android developers about.

Ideally I would be able to select a single build variant when clicking on the debug button, but I have not discovered a way to modify the default debug build behavior.

**Comment by neutrinog** [comment]
@jag3773 hooray! I finally figured out how to get it working. and it's super easy. :)
