### ISSUE TITLE
Toggle to View Larger Sections

### ISSUE THREAD

**Issue by jag3773** [Door43/translationStudio2#53]
Provide a way to show longer sections of text so that translators can get the greater context, especially for sections of discourse.

The issue is that the text will be broken down into frames of 1 to several verses.  This will be break pont for entering a translation.  However, it will be necessary to view larger sections than this in the source texts whenever the translator wants to zoom out a bit.

**Comment by neutrinog** [comment]
also related to https://github.com/Door43/translationStudio2/issues/247

**Comment by neutrinog** [comment]
This will be a full screen view. e.g. The translation input on the right will not be visible when this mode is active.

**Comment by neutrinog** [comment]
We'll place a button in the bottom corner of the window that when clicked will display a menu list of actions. Since we will combine actions for both the source and translations let's go ahead and place this button in the bottom *right* corner instead of the left corner.

**Here's is an example:**

![untitled_clipping_040615_100403_am](https://cloud.githubusercontent.com/assets/166412/7008401/1db38ba8-dc47-11e4-9bf6-f3d5d166121f.jpg)

> Please note: the menu does not need to look like the image above, this is just an example.

When clicking on the appropriate action a new modal window should be displayed showing the scrollable text. The `DialogFragment` will probably work best for this. Look in the dialogs directory for examples.

**Comment by neutrinog** [comment]
@HannaJaicks I'm thinking we could use a list view in the dialog. Then each item in the list will be the contents of a frame. Then we can allow users to view all of the frames, but start focused on the frame they were viewing first.

**Comment by neutrinog** [comment]
@HannaJaicks I think we might want to display the frame number as headings in the frame list as well.

**Comment by neutrinog** [comment]
@HannaJaicks Let's hide the button when no frame is selected. For example, when someone installs the app for the first time they will not have selected a frame yet.

**Comment by neutrinog** [comment]
@HannaJaicks Could we also place an icon in the center of the button?
Something like this to illustrate it's a menu. The red is just to illustrate it. White would probably be a better choice :)


![screenshot_041415_010223_pm](https://cloud.githubusercontent.com/assets/166412/7146192/94a99a76-e2a6-11e4-980d-fce8a8c11f42.jpg)
